FLASK_ADMIN_SWATCH = 'cerulean'

SECURITY_URL_PREFIX = '/users'
SECURITY_REGISTERABLE = True
SECURITY_RECOVERABLE = True
SECURITY_USER_IDENTITY_ATTRIBUTES = ['username', 'email', 'mobile']
SECURITY_SEND_REGISTER_EMAIL = False
SECURITY_SEND_PASSWORD_CHANGE_EMAIL = False
SECURITY_SEND_PASSWORD_RESET_EMAIL = False
SECURITY_SEND_PASSWORD_RESET_NOTICE_EMAIL = False

FLORIST_ADMIN_USERNAME = 'admin'
FLORIST_ADMIN_MOBILE = '13000000000'
FLORIST_ADMIN_EMAIL ='admin@example.com'
FLORIST_ADMIN_PASSWORD = 'nimda321'
